// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExampleRepository is an autogenerated mock type for the ExampleRepository type
type ExampleRepository struct {
	mock.Mock
}

// GetExampleTaxValue provides a mock function with given fields: firstParm, secondParam
func (_m *ExampleRepository) GetExampleTaxValue(firstParm int, secondParam int) int {
	ret := _m.Called(firstParm, secondParam)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(firstParm, secondParam)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
