name: Automatic review with static code analyzer

on:
  push

env:
  GO111MODULE: on
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
# We run `release` this create a release from the master branch
jobs:
  check-app:
    runs-on: ubuntu-latest   
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18  
    
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest 

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
         
    - name: Run revive      
      run: go install github.com/mgechev/revive@latest  

    - name: Run golangci-lint      
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2
 
    - name: Run misspell check spelling     
      run:  go get -u github.com/client9/misspell/cmd/misspell
    
    - name: Run unparam to check for unused params    
      run:  go install mvdan.cc/unparam@latest

    - name: Setup security linter
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run reviewdog github-check
      continue-on-error: true      
      run: reviewdog -reporter=github-check  

    - name: Run reviewdog pr-review 
      continue-on-error: true     
      run: reviewdog -reporter=github-pr-review

  gocritic-lint:
    runs-on: ubuntu-latest   
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18 
    - name: Setup go critic
      run: go install github.com/go-critic/go-critic/cmd/gocritic@latest  
    - name: Run go critic
      run: gocritic check ./...
      
  hadolint:
    name: check docker files
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: github-check
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check # Default is github-pr-check
